[phases.setup]
# Python version set कर रहे हैं
nixPkgs = ["python310"]

[phases.install]
cmds = [
  "pip install -r requirements.txt"
]

[phases.build]
# अगर collectstatic चलाना हो (Django में)
cmds = [
  "python manage.py collectstatic --noinput"
]

[start]
# App run करने का command (Gunicorn के साथ)
cmd = "gunicorn smart_task_manager.wsgi:application --bind 0.0.0.0:$PORT"
