# Base image
FROM python:3.11-slim

# Working directory
WORKDIR /app

# Dependencies install
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Collect static files
RUN python manage.py collectstatic --noinput

# Expose port
EXPOSE 8000

# Start server
CMD ["gunicorn", "smart_task_manager.wsgi:application", "--bind", "0.0.0.0:8000"]

